
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;


/**
 *
 * @author Matthias
 */
public class VelocityDlg extends javax.swing.JDialog {

    private Measurement measurement = null;
    
    public VelocityDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfDate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfTime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfKennzeichen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfMeasured = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfLegal = new javax.swing.JTextField();
        btAdd = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(6, 2));

        jLabel1.setText("Datum:");
        getContentPane().add(jLabel1);

        tfDate.setText("29.02.2017");
        getContentPane().add(tfDate);

        jLabel2.setText("Uhrzeit:");
        getContentPane().add(jLabel2);

        tfTime.setText("07:55");
        getContentPane().add(tfTime);

        jLabel3.setText("Kennzeichen:");
        getContentPane().add(jLabel3);

        tfKennzeichen.setText("GU-SPOOKY-1");
        getContentPane().add(tfKennzeichen);

        jLabel4.setText("V-Gemessen:");
        getContentPane().add(jLabel4);

        tfMeasured.setText("123");
        getContentPane().add(tfMeasured);

        jLabel5.setText("V-Erlaubt:");
        getContentPane().add(jLabel5);

        tfLegal.setText("80");
        getContentPane().add(tfLegal);

        btAdd.setText("Übernehmen");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });
        getContentPane().add(btAdd);

        btCancel.setText("Abbrechen");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btCancel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        try {
            String dateTimeStr = String.format("%s %s", tfDate.getText(), tfTime.getText());
            LocalDateTime dateTime = LocalDateTime.parse(dateTimeStr, DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm"));
            double measured = Double.parseDouble(tfMeasured.getText());
            double legal = Double.parseDouble(tfLegal.getText());

            measurement = new Measurement(dateTime, tfKennzeichen.getText(), measured, legal);
            this.dispose();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Pleas make sure to enter doubles, and to enter the date and time in the correct format");
        }
    }//GEN-LAST:event_btAddActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        measurement = null;
        this.dispose();
    }//GEN-LAST:event_btCancelActionPerformed

    public Measurement getMeasurement() {
        return measurement;
    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VelocityDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VelocityDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VelocityDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VelocityDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VelocityDlg dialog = new VelocityDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tfDate;
    private javax.swing.JTextField tfKennzeichen;
    private javax.swing.JTextField tfLegal;
    private javax.swing.JTextField tfMeasured;
    private javax.swing.JTextField tfTime;
    // End of variables declaration//GEN-END:variables
}
